### ISSUE TITLE
Building a standalone web component

### ISSUE THREAD

**Issue by dremekie** [kchobantonov/jsonforms-vuetify-webcomponent#5]
Hi. This is very nice work you've done with this forms library.

**My question:** How can I use the example [here](https://github.com/kchobantonov/jsonforms-vuetify-webcomponent?tab=readme-ov-file#loading-from-cdn) with the current version of this repo? Basically, how would I build something like `https://cdn.jsdelivr.net/npm/@chobantonov/jsonforms-vuetify-webcomponent@3.1.0-alpha.3/dist/vuetify-json-forms.min.js`?

**Comment by kchobantonov** [comment]
yes the current version which is based on vue3 and vuetify3 in the master branch is currently not yet released since I'm waiting for few more issues to be resolved before the release. I expect that most likely in about few weeks there will be a release that you can use - either the the fixes that I'm talking about or without them depending on how much changes are neededed in the jsonforms project

**Comment by dremekie** [comment]
👍 Thanks for the update.

**Comment by dremekie** [comment]
Hi @kchobantonov Any update on this? I'm very keen to use and help test a webcomponent of this.
